# Generated by Django 4.2.18 on 2025-02-08 09:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user', 'quiz_id', 'question_id', 'attempt_number')},
        ),
    ]
