# Generated by Django 5.1.5 on 2025-02-04 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinLengthValidator(0.0), django.core.validators.MaxLengthValidator(5.0)]),
        ),
    ]
