# Generated by Django 5.1.5 on 2025-02-04 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_topic_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
