# Generated by Django 4.2.18 on 2025-02-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_user_id_userresponse_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='quiz_points',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
