# Generated by Django 4.2.18 on 2025-02-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_point_quiz_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='best_point',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
