# Generated by Django 4.2.18 on 2025-02-09 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_alter_attempt_best_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global_points',
            name='id',
        ),
        migrations.AlterField(
            model_name='global_points',
            name='total_points',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='global_points',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
