# Generated by Django 5.1.5 on 2025-02-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_topic_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='quiz_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
