# Generated by Django 4.2.18 on 2025-02-11 10:10

from django.db import migrations, models
import quiz.validators


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='number_of_attempt',
            field=models.IntegerField(validators=[quiz.validators.validate_attempt]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='difficulty_level',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('X', 'Expert')], default='E', max_length=1, validators=[quiz.validators.validate_levels]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=70, validators=[quiz.validators.validate_topic_name]),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='attempt_number',
            field=models.IntegerField(validators=[quiz.validators.validate_attempt]),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='user_ans',
            field=models.CharField(max_length=200, validators=[quiz.validators.validate_user_answer]),
        ),
    ]
