# Generated by Django 5.1.6 on 2025-02-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_userresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='topic_id',
            new_name='quiz_id',
        ),
    ]
