# Generated by Django 4.2.18 on 2025-02-06 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0016_attempt_global_points'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('user_id', 'quiz_id')},
        ),
    ]
