# Generated by Django 4.2.18 on 2025-02-07 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0017_alter_attempt_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='attempt_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user_id', 'quiz_id', 'question_id', 'attempt_number')},
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user_response_id',
        ),
    ]
