# Generated by Django 4.2.18 on 2025-02-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_userresponse_attempt_number_userresponse_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together=set(),
        ),
    ]
