# Generated by Django 4.2.18 on 2025-02-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_alter_userresponse_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='attempt_number',
        ),
    ]
