# Generated by Django 4.2.18 on 2025-02-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_remove_userresponse_attempt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='id',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='user_response_id',
            field=models.BigAutoField(default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
