# Generated by Django 4.2.18 on 2025-02-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_userresponse_attempt_number_userresponse_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='user_response_id',
            field=models.BigAutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='id',
        ),
    ]
