# Generated by Django 4.2.18 on 2025-02-07 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0023_alter_userresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='attempt_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user_id', 'quiz_id', 'question_id', 'attempt_number')},
        ),
    ]
