# Generated by Django 4.2.18 on 2025-02-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_userresponse_attempt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='user_response_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
