# Generated by Django 4.2.18 on 2025-02-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_alter_userresponse_user_response_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='user_response_id',
            new_name='id',
        ),
    ]
